# Import Pandas, MySQL, & SQL Library

In [76]:
import pandas as pd
import pymysql
import sqlalchemy

print("All packages imported successfully!")

All packages imported successfully!

# Make a connection of Python to MySQL

In [77]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Anugya%4012%23@127.0.0.1:3306/files")

# Importing the JSON library to read and extract the data from JSON file

In [78]:
import json
p = open('ecommerce_50000_orders.json')
data = json.load(p)
print(data.keys())

dict_keys(['orders'])

In [34]:
orders = data['orders']
orders[0]

{'order_id': 1,
 'order_date': '2025-08-03',
 'customer': {'customer_id': 489,
  'customer_name': 'Customer_489',
  'city': 'Kolkata'},
 'payment': {'payment_method': 'Wallet', 'status': 'Success'},
 'items': [{'product_id': 60,
   'product_name': 'Product_60',
   'category': 'Fashion',
   'quantity': 2,
   'price': 11292},
  {'product_id': 192,
   'product_name': 'Product_192',
   'category': 'Sports',
   'quantity': 2,
   'price': 39154},
  {'product_id': 262,
   'product_name': 'Product_262',
   'category': 'Sports',
   'quantity': 4,
   'price': 7742}]}

In [25]:
# Making these tables from the JSON file.

# orders = order_id, order_date, customer_id
# customers = customer_id, customer_name, city
# payment = order_id, payment_method, status
# products = product_id, product_name, category, price
# order_items = order_id, product_id, quantity

In [91]:
# Making a empty list for each table .
orders_data = []
customers_data = []
payment_data = []
products_data = []
order_items_data = []

In [92]:
for order in orders:

    orders_data.append({
        'order_id': order['order_id'],
        'order_date': order['order_date'],
        'customer_id': order['customer']['customer_id']

    })

    customers_data.append({
        'customer_id': order['customer']['customer_id'],
        'customer_name': order['customer']['customer_name'],
        'city': order['customer']['city']
    })

    payment_data.append({
        'order_id': order['order_id'],
        'payment_method': order['payment']['payment_method'],
        'status': order['payment']['status']
    })

    for item in order['items']:

        products_data.append({
            'product_id': item['product_id'],
            'product_name': item['product_name'],
            'category': item['category']
        })

        order_items_data.append({
            'order_id': order['order_id'],
            'product_id': item['product_id'],
            'quantity': item['quantity'],
            'price': item['price']
        })

In [96]:
orders_df = pd.DataFrame(orders_data)
customers_df = pd.DataFrame(customers_data)
payment_df = pd.DataFrame(payment_data)
products_df = pd.DataFrame(products_data)
order_items_df = pd.DataFrame(order_items_data)

# Removes duplicates from customers and products table

In [109]:
customers_df.drop_duplicates(subset='customer_id', keep='last' , inplace=True)
products_df.drop_duplicates(subset='product_id', keep='last' , inplace=True)
order_items_df

        order_id  product_id  quantity  price  Total_Amount
0              1          60         2  11292         22584
1              1         192         2  39154         78308
2              1         262         4   7742         30968
3              2         217         2  10301         20602
4              2         250         5  27461        137305
...          ...         ...       ...    ...           ...
125446     49999         144         3  25108         75324
125447     50000          83         4  18988         75952
125448     50000         190         5  29050        145250
125449     50000          50         5  21818        109090
125450     50000         212         4   4732         18928

[125451 rows x 5 columns]

# Check for Missing value

In [110]:
orders_df.isnull().sum()
customers_df.isnull().sum()
payment_df.isnull().sum()
products_df.isnull().sum()
order_items_df.isnull().sum()

order_id        0
product_id      0
quantity        0
price           0
Total_Amount    0
dtype: int64

# Validating the Data Types

In [111]:
orders_df.info()
customers_df.info()
payment_df.info()
products_df.info()
order_items_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50000 non-null  int64
 1   order_date   50000 non-null  datetime64[us]
 2   customer_id  50000 non-null  int64
 3   year         50000 non-null  int32
 4   month        50000 non-null  int32
dtypes: datetime64[us](1), int32(2), int64(2)
memory usage: 1.5 MB
<class 'pandas.DataFrame'>
Index: 2000 entries, 34611 to 49999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    2000 non-null   int64
 1   customer_name  2000 non-null   str
 2   city           2000 non-null   str
dtypes: int64(1), str(2)
memory usage: 62.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50000 non-null  int64
 1   payment_method  50000 non-null  str
 2   status          50000 non-null  str
dtypes: int64(1), str(2)
memory usage: 1.1 MB
<class 'pandas.DataFrame'>
Index: 300 entries, 123334 to 125450
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    300 non-null    int64
 1   product_name  300 non-null    str
 2   category      300 non-null    str
dtypes: int64(1), str(2)
memory usage: 9.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 125451 entries, 0 to 125450
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      125451 non-null  int64
 1   product_id    125451 non-null  int64
 2   quantity      125451 non-null  int64
 3   price         125451 non-null  int64
 4   Total_Amount  125451 non-null  int64
dtypes: int64(5)
memory usage: 4.8 MB

# Check for Invalid Values

In [112]:
order_items_df[order_items_df['quantity'] <= 0]
order_items_df[order_items_df['price'] <= 0]
order_items_df.head(5)

   order_id  product_id  quantity  price  Total_Amount
0         1          60         2  11292         22584
1         1         192         2  39154         78308
2         1         262         4   7742         30968
3         2         217         2  10301         20602
4         2         250         5  27461        137305

# Calculate Total Amount

In [113]:
order_items_df['Total_Amount'] = order_items_df['price'] * order_items_df['quantity']
order_items_df.head(10)

   order_id  product_id  quantity  price  Total_Amount
0         1          60         2  11292         22584
1         1         192         2  39154         78308
2         1         262         4   7742         30968
3         2         217         2  10301         20602
4         2         250         5  27461        137305
5         2          89         5  12778         63890
6         2          86         4  11948         47792
7         3          28         3  16098         48294
8         3           5         4  30544        122176
9         3          70         2  46545         93090

# Convert date to Datetime

In [114]:
orders_df['order_date'] = pd.to_datetime(orders_df['order_date'])

# Extract date components

In [115]:
orders_df['year'] = orders_df['order_date'].dt.year
orders_df['month'] = orders_df['order_date'].dt.month
orders_df['month'].head(5)

0    8
1    5
2    9
3    5
4    2
Name: month, dtype: int32

In [ ]:
orders_df.to_sql(name = 'orders', con=engine, index = False, if_exists= 'replace' )
customers_df.to_sql(name = 'customers', con=engine, index = False, if_exists= 'replace' )
payment_df.to_sql(name = 'payments', con=engine, index = False, if_exists= 'replace' )
products_df.to_sql(name = 'products', con=engine, index = False, if_exists= 'replace' )
order_items_df.to_sql(name = 'order_items', con=engine, index = False, if_exists= 'replace' )

300